### ISSUE TITLE
Fix the packages to a version we know works forever until we need to update.

### ISSUE THREAD

**Issue by diegobaronm** [tzuhanchang/HyPER#50]
As the title says...

**Comment by tzuhanchang** [comment]
`pytorch_lightning` has removed the support to `_TORCH_GREATER_EQUAL_2_0`, see this [pull request](https://github.com/Lightning-AI/pytorch-lightning/pull/19706). This raised a issue in `HyPER.onnx`. @diegobaronm suggests updating environment file with fixed version, preventing similar issues from happening.
